####
# ATENTION:
# Replace all occurences of confee with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  confee-postgres-data:
    driver: local

  # MySQL Data
  confee-mysql-data:
    driver: local

  # Redis Data
  confee-redis-data:
    driver: local

services:
  # Postgres (10.3)
  postgres:
    image: postgres:10.3
    container_name: confee-postgres
    volumes:
      - confee-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=confee
      - POSTGRES_DB=confee
      - POSTGRES_USER=confee

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: confee-mysql
    volumes:
      - confee-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=confee
      - MYSQL_DATABASE=confee
      - MYSQL_USER=confee
      - MYSQL_PASSWORD=confee

  # Redis
  cache:
    image: redis:4.0
    container_name: confee-redis
    command: --appendonly yes
    volumes:
      - confee-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  api:
    image: ambientum/php:7.2-nginx
    container_name: confee-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: confee-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache